In [2]:
# numpy je base-library za neke druge kao npr pandas ili openCV koja je image-prossesing library
import numpy
import cv2

In [3]:
im_g=cv2.imread("smallgray.png",0)  # 0-ocitavanje slike u gray, 1-u BGR
im_g                                # brojevi reprezenti manje-tamnije, bilo-255, crno-97

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
im_g.shape

(3, 5)

In [4]:
im_g[0:2]   #Standradno slajsanje: dobijemo 1 i 2 element(listu1 i 2)

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [5]:
im_g[0:2,2:4]   #slajsanje kolona 2 i 3 reda 1 i 2)

array([[104, 121],
       [255, 255]], dtype=uint8)

In [7]:
im_g[:,2:4]   #varijacija_slajsanje kolona 2 i 3 svakog reda

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [8]:
im_g[2,4]   #varijacija_slajsanje celije na krizanju 2reda i 4te kolone

182