In [17]:
# numpy je base-library za neke druge kao npr pandas ili openCV koja je image-prossesing library
import numpy
import cv2

In [18]:
im_g=cv2.imread("smallgray.png",0)  # 0-ocitavanje slike u gray, 1-u BGR
im_g                                # brojevi reprezenti manje-tamnije, bilo-255, crno-97

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
im_g.shape

(3, 5)

In [20]:
im_g[0:2]   #Standradno slajsanje: dobijemo 1 i 2 element(listu1 i 2)

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [21]:
im_g[0:2,2:4]   #slajsanje kolona 2 i 3 reda 1 i 2)

array([[104, 121],
       [255, 255]], dtype=uint8)

In [22]:
im_g[:,2:4]   #varijacija_slajsanje kolona 2 i 3 svakog reda

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [23]:
im_g[2,4]   #varijacija_slajsanje celije na krizanju 2reda i 4te kolone

182

In [24]:
for i in im_g: # i predstavlja redove-liste
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [25]:
for i in im_g.flat: # i sad predstavlja pojedine celije koje smo prije dobijali sa dva for-a
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [26]:
for i in im_g.T: # i sad kod transponirane matrice predstavlja kolone-liste
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [27]:
# Stacking-spajanje manjih u jednu i splitanje vecih (array-i ISTE DIMENZIJE inace ERROR)
ims=numpy.hstack((im_g,im_g))   #horizontal stack sa dva array-a (ili 2x isti ako nemamo) ali u tuplu
ims         # i dobili smo mergane adekvatne elemente

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
ims=numpy.hstack((im_g,im_g,im_g))   #horizontal stack sa vise (3) array-a 
ims         # i dobili smo mergane adekvatne elemente koji radi boljeg izgleda printamo
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [29]:
ims=numpy.vstack((im_g,im_g,im_g))   #vertikalni stack sa vise (3) array-a 
ims         # i dobili smo mergane adekvatne elemente koji se prosto dodaju nakon sto je cijeli ispred izlistan
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [30]:
lst=numpy.vsplit(ims,3) # splitanje vertikalno, argumenti array i broj djelova koji mora biti djelitelj redova
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [31]:
lst=numpy.hsplit(ims,5) # splitanje horizontalno, argumenti array i broj djelova koji mora biti djelitelj kolona
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]
